apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: chart-repo
  namespace: microservices-demo
spec:
  interval: 1m
  url: https://github.com/Nicola-Sergio/microservices-demo/
  ref:
    branch: develop
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    