apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: productcatalogservice-helmrelease
  namespace: microservices-demo
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  releaseName: productcatalogservice
  targetNamespace: microservices-demo
  interval: 5m
  chart:
    spec:
      chart: ./charts/microservice
      version: "0.1.4"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values: 
    service:
      name: productcatalogservice
      type: ClusterIP
      selectors:
        app: productcatalogservice
      port: 3550
      targetPort: 3550
    deployment:
      name: productcatalogservice
      labels:
        app: productcatalogservice
      matchLabels:
        app: productcatalogservice
      container:
        name: server 
    image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
    ingress:
      enabled: true
      name: productcatalogservice-ingress
      path : "/"
      path_type: Prefix
      host: 
        enabled: false
        name: productcatalogservice
    env:
    - name: PORT
      value: "3550"
    - name: DISABLE_PROFILER
      value: "1"