apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/ingress-nginx
      sourceRef:
        kind: GitRepository
        name: nginx-ingress
        namespace: nginx-ingress-controller
      interval: 1m
  values:
    replicaCount: 2
