# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: nginx-ingress
#   namespace: nginx-ingress-controller
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: ./charts/ingress-nginx
#       sourceRef:
#         kind: GitRepository
#         name: nginx-ingress
#         namespace: nginx-ingress-controller
#       interval: 1m
#   values:
#     replicaCount: 2
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress-controller
spec:
  interval: 5m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx-helmrepo
        namespace: nginx-ingress-controller
  values: 
    controller:
      addHeaders: 
        client-max-body-size: 50M
        keep-alive: "3600"
        proxy-buffer-size: 500m
        proxy-buffers-number: "8" 

 

