# apiVersion: source.toolkit.fluxcd.io/v1
# kind: GitRepository
# metadata:
#   name: nginx-ingress
#   namespace: nginx-ingress-controller
# spec:
#   interval: 1m
#   url: https://github.com/kubernetes/ingress-nginx/
#   ref:
#     branch: main
#   ignore: |
#     # exclude all
#     /*
#     # include charts directory
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-helmrepo
  namespace: nginx-ingress-controller
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx
