apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  {{- if .Values.service.enabled}}
  labels:
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- with .Values.service.selectors }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
